---
roles:
  - name: stackhpc.os-flavors
  - name: stackhpc.os-images
  - name: stackhpc.os-networks
    source: git@github.com:stackhpc/ansible-role-os-networks.git
    type: git
    version: v1.5.7
  - name: stackhpc.os-projects
  - name: stackhpc.os_host_aggregates
  - name: stackhpc.os-container-clusters

collections:
  - name: openstack.cloud
    version: '<2'
